-- Create vocabulary table
CREATE TABLE public.vocabulary (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  spanish TEXT NOT NULL,
  english TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.vocabulary ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Vocabulary is publicly readable" 
ON public.vocabulary 
FOR SELECT 
USING (true);

-- Insert all vocabulary data
INSERT INTO public.vocabulary (spanish, english) VALUES
('Norteamericano', 'American (m)'),
('Usted', 'You (formal)'),
('Señorita', 'Miss'),
('Un poco', 'A little'),
('Habla', 'You speak (formal)'),
('Español', 'Spanish (language)'),
('Hablo', 'I speak'),
('Sí', 'Yes'),
('¿Entiende?', 'Do you understand? (formal)'),
('Inglés', 'English (language)'),
('Disculpe.', 'Excuse me.'),
('No entiendo.', 'I don''t understand.'),
('Señora', 'Ma''am/Mrs.'),
('Cómo', 'How'),
('Adiós.', 'Good-bye.'),
('¿Cómo está?', 'How are you? ("You" understood, formal)'),
('Buenos días.', 'Good morning.'),
('Gracias', 'Thank you/thanks'),
('¿Cómo está usted?', 'How are you? (formal)'),
('Bien', 'Fine/Good/Well'),
('Norteamericana', 'American (f)'),
('Muy', 'Very'),
('La noche', 'The night/the evening'),
('¿Dónde?', 'Where?'),
('El día', 'The day'),
('y', 'and'),
('La tarde', 'The afternoon'),
('Soy', 'I am'),
('Muy bien', 'Ok, very well'),
('Buenas noches', 'Good night/good evening'),
('Buenas tardes', 'Good afternoon'),
('El señor', 'Mr.'),
('De', 'from'),
('Está aquí', 'It''s here'),
('Soy mexicana', 'I am mexican (f)'),
('No está aquí', 'It''s not here'),
('Aquí', 'Here'),
('Nos vemos.', 'See you.'),
('Está', 'It is, you are'),
('Encantada', 'Pleased to meet you (f)'),
('Allí', 'Over there/there'),
('Encantado', 'Pleased to meet you (m)'),
('El restaurante', 'The restaurant'),
('El hotel', 'The hotel'),
('Estados Unidos', 'United States'),
('Un', 'A/one (m)'),
('Tú sabes', 'You know (informal)'),
('Sólo', 'Only'),
('Por favor', 'Please'),
('Sí, sé', 'Yes, I know.'),
('Sé', 'I know.'),
('Un peso', 'One peso'),
('Tengo', 'I have'),
('¿Sabe?', 'Do you know? (formal)'),
('Un dólar', 'A dollar'),
('Tres', 'Three'),
('Está bien.', 'That''s okay.'),
('Cien', 'One hundred'),
('Mucho', 'much (m)'),
('Quiero', 'I want'),
('Muchos', 'Many/a lot/lots (plural, m)'),
('¿Cuántos?', 'How many?'),
('Dos', 'Two'),
('Doscientos', 'Two hundred'),
('Muchas gracias', 'Thank you very much/thanks a lot'),
('Yo', 'I/me'),
('Tú entiendes', 'You understand (informal)'),
('Tú quieres', 'You want (informal)'),
('Pero', 'But'),
('Cinco', 'Five'),
('¿Qué?', 'What?'),
('Treinta', 'Thirty'),
('Cuatro', 'Four'),
('Nada', 'Nothing/anything'),
('Algo', 'Something'),
('Vamos.', 'Let''s go.'),
('No quiero nada.', 'I don''t want anything.'),
('Comer', 'To eat'),
('Cuatrocientos', 'Four hundred'),
('Nada, gracias', 'Nothing, thanks.'),
('Una', 'A/One (f)'),
('Cuánto', 'How much (singular)'),
('Tomar', 'To drink'),
('O', 'Or'),
('Cuesta', '(it) costs/(does it) cost'),
('Doce', 'Twelve'),
('Una cerveza', 'A beer'),
('Un refresco', 'A soda'),
('Seis', 'Six'),
('Siete', 'Seven'),
('El baño', 'The bathroom'),
('Ocho', 'Eight'),
('No es nada.', 'It''s nothing/It''s not anything'),
('Pagar', 'To pay'),
('¡Hola!', 'Hello!/Hi!'),
('Yo también', 'Me too'),
('Nueve', 'Nine'),
('Tiempo', 'Time'),
('Dinero', 'Money'),
('Un minuto', 'One/a minute'),
('Tú vas?', 'Are you going? (informal)'),
('Yo voy', 'I''m going'),
('¿adónde?', 'Where? (lit., to where?)'),
('También', 'Also/too'),
('Once', 'Eleven'),
('Me gusta.', 'I like (it).'),
('¿Por qué?', 'Why?'),
('Bueno', 'Good/all right (m)'),
('Diez', 'Ten'),
('fría', 'Cold (f)'),
('Agua', 'Water'),
('De nada.', 'You''re welcome.'),
('¿Por qué no?', 'Why not?'),
('Porque', 'Because'),
('U', 'Or (before words beginning with an ''o'' sound)'),
('¿Cuántas?', 'How many? (f)'),
('Buena', 'Good (f)'),
('La panadería', 'The bakery'),
('Cosas', 'Things'),
('Le gusta', 'You like (formal)'),
('Hay', 'There is/there are'),
('Comprar', 'To  buy'),
('Trece', 'Thirteen'),
('Puedo', 'I can'),
('Si', 'If'),
('Tú puedes', 'You can (informal)'),
('Compro', 'I buy'),
('Como', 'I eat'),
('Hoy', 'Today'),
('Vainilla', 'Vanilla'),
('Hoy no.', 'Not today.'),
('Mañana', 'Tomorrow'),
('Quince', 'Fifteen'),
('Horas', 'Hours'),
('Catorce', 'Fourteen'),
('Pago', 'I pay'),
('¿A qué hora?', 'At what time?'),
('Tomarla', 'To drink it (f)'),
('Cuarto', 'Quarter (with time)/fifteen'),
('Tomo', 'I drink'),
('Refrescos', 'Sodas'),
('Comprarla', 'To buy it (f)'),
('Pagarlas', 'To pay for them'),
('Menos cuarto', 'Quarter to (the hour)'),
('Dieciséis', 'Sixteen'),
('Ahora', 'Now'),
('Tú comes', 'You eat (informal)'),
('Diecisiete', 'Seventeen'),
('Cuestan', 'They cost'),
('Diecinueve', 'Nineteen'),
('Dieciocho', 'Eighteen'),
('Media', 'Half'),
('Veinte', 'Twenty'),
('Temprano', 'Early'),
('Una hora y media', 'An hour and a half'),
('Tarde', 'Late'),
('Hablar', 'To speak/talk'),
('Más tarde', 'Later'),
('Lo', 'It (m)'),
('Cuarenta', 'Forty'),
('¿Qué hora es?', 'What time is it?'),
('Contigo', 'With you (informal)'),
('Hacer', 'To do'),
('Quién', 'Who/whom'),
('Él', 'He'),
('Cuatrocientos Cuarenta', 'Four hundred and forty'),
('Él puede', 'He can'),
('Él sabe', 'He knows'),
('Veintiséis', 'Twenty-six'),
('Cincuenta', 'Fifty'),
('Veintiún minutos', 'Twenty-one minutes'),
('Juntos', 'Together'),
('Con', 'With'),
('Demasiado', 'Too much'),
('¿Quién va?', 'Who''s going?'),
('Él tiene', 'He has'),
('Nosotros', 'We/us'),
('Un amigo', 'A friend (m)'),
('Tenemos', 'We have'),
('Sola', 'Alone (f)'),
('Ella', 'She'),
('Esposo', 'Husband'),
('Cuarenta y ocho', 'Forty-eight'),
('Veintitrés', 'Twenty-three'),
('Setenta', 'Seventy'),
('Esposa ', 'Wife'),
('Queremos', 'We want'),
('Amigos', 'Friends'),
('Mi', 'My'),
('Hablamos', 'We speak'),
('Somos', 'We are'),
('Mis', 'My (plural)'),
('Podemos', 'We can'),
('Noventa', 'Ninety'),
('Tomamos', 'We drink'),
('Quizá', 'Maybe'),
('Sabemos', 'We know'),
('Nuestros', 'Our (plural)'),
('Tus', 'Your (plural, informal)'),
('Ya me voy.', 'Right now I''m leaving.'),
('Ciento diez', 'One hundred ten'),
('Suficiente', 'Enough'),
('Van', 'They''re going'),
('Come', 'He eats/she eats (informal)'),
('Nuestro', 'Our (m, singular)'),
('Las personas', 'The people'),
('Nos vamos', 'We''re leaving/we are going away'),
('Lista', 'Ready (f)'),
('Estoy', 'I am'),
('Me voy', 'I''m leaving/going away'),
('Saber', 'To know'),
('De la tarde', 'In the afternoon'),
('Números', 'Numbers'),
('Ochenta y tres', 'Eighty-three'),
('¿Cuándo?', 'When?'),
('Todos', 'All/everybody/all of us'),
('Se van', 'They''re leaving'),
('Una semana', 'A week'),
('Ciento diecinueve', 'One hundred nineteen'),
('De vacaciones', 'On vacation'),
('Este', 'This (m)'),
('Hombre', 'Man'),
('La persona', 'The person'),
('Rápido', 'Fast/quickly'),
('Estar', 'To be'),
('Ciento dieciocho', 'One hundred eighteen'),
('Dime --', 'Tell me (informal)'),
('Más despacio', 'Slower'),
('Esta', 'This (f)'),
('Verdad', 'True/right'),
('A la una.', 'At one o''clock.'),
('Hablan', 'They speak'),
('Un té', 'A tea'),
('Norteamericanos', 'Americans (noun, m, plural)'),
('Enfermas', 'Sick (f, plural)'),
('Pequeños', 'Small, little (m, plural)'),
('Ese', 'That (m)'),
('Mujer/mujeres', 'Woman/women'),
('¿verdad?', 'Isn''t he/she?'),
('Una taza', 'A cup'),
('Grande', 'Big, large'),
('Enferma', 'Sick (f)'),
('Un vaso', 'A glass'),
('Esa', 'That/that one (f)'),
('Pequeña', 'Small, little (f)'),
('Están', 'They are'),
('Escríbelo.', 'Write it (down). (m, informal)'),
('Creo que sí.', 'I think so.'),
('Enfermos', 'Sick (m, plural)'),
('Tú dices', 'You say (informal)'),
('¿Cuál?', 'Which (one)?/What?'),
('Creo que no.', 'I don''t think so.'),
('Buen', 'Good (m, singular)'),
('Yo necesito', 'I need'),
('Yo creo', 'I think'),
('Un médico', 'A doctor'),
('El número de teléfono', 'A (tele)phone number'),
('Te llamas', 'Your name is (informal)'),
('La calle', 'The street'),
('Me llamo', 'My name is'),
('Lejos', 'Far (away)'),
('Vivo', 'I live'),
('Tú crees', 'You think/believe (informal)'),
('La dirección', 'The address'),
('Recuerdo', 'I remember'),
('Cerca', 'Near(by)/close'),
('¿Como se llama?', 'What''s his/her name?'),
('Escríbela', 'Write it (down) (f, informal)'),
('Siempre', 'Always'),
('A la derecha', 'To (on) the right'),
('Luego', 'Then'),
('Por aquí', 'This way'),
('Avenida', 'Avenue'),
('Escribir', 'To write'),
('Derecho', 'Straight/straight ahead'),
('A la izquierda', 'To (on) the left'),
('Por allí', 'That way'),
('Aprendo', 'I learn'),
('Estás enfermo', 'You are sick (m, informal)'),
('Estudiar', 'To study'),
('Aprender', 'To learn'),
('Esa palabra', 'That word'),
('Que significa', 'What it means'),
('Estudias', 'You study (informal)'),
('Mi padre', 'My father'),
('Ir', 'To go'),
('No importa.', 'It does not matter.'),
('Ver a una persona', 'To see a person'),
('Otra vez', 'Again/another time'),
('Veces', 'Times'),
('Conmigo', 'With me'),
('Ven conmigo.', 'Come with me. (informal)'),
('Casa', 'House'),
('Venir', 'To come'),
('Visto', 'Seen'),
('Película', 'Movie/Film'),
('¿Lo has visto?', 'Have you (informal) seen him?'),
('Ayer', 'Yesterday'),
('Verla', 'To see her'),
('Cuadras', '(City) blocks'),
('Por teléfono', 'By phone/on the phone'),
('Hablado', 'Spoken'),
('Excelente', 'Excellent'),
('Suficientes', 'Enough (plural)'),
('Estudiado', 'Studied'),
('En casa', 'At home'),
('Al cine', 'To the movies'),
('Dicho', 'Told/said'),
('Esperar', 'To wait'),
('Hemos hablado español.', 'We have spoken Spanish.'),
('Películas', 'Movies/Films'),
('Ha vivido', 'She/he has lived'),
('Me han dicho', 'They have told me.'),
('Comido', 'Eaten'),
('Madre', 'Mother'),
('¡Espera!', 'Wait! (Informal)'),
('Tengo que', 'I have to'),
('Todavía', 'Still/yet'),
('Eso', 'That (m, pronoun)'),
('Mole', 'Mole (A mexican dish)'),
('Mucho tiempo', 'A long time'),
('Leche', 'Milk'),
('Otra cosa', 'Something else'),
('Ayudarlo', 'to help him'),
('Un momentito', '(In) just a moment'),
('Decirte', '(To) say to you/Tell you (informal)'),
('Con mucho gusto.', 'Gladly. / With much pleasure.'),
('Hasta pronto.', 'See you soon.'),
('Nuestra', 'Our (f)'),
('Momento', 'Moment'),
('Irme', 'To leave (used with "I")'),
('Ayudar', 'To help'),
('Tenemos que', '(We) have to'),
('¿Qué tal?', 'How''s it going?'),
('Usted conoce', '(You) know / are acquainted with (formal)'),
('Entonces', 'In that case'),
('Has estado', 'You have been (informal)'),
('Alguien', 'Somebody/someone'),
('Prefiero', '(I) prefer'),
('Cómo no.', 'Certainly./Sure.'),
('La gente', 'The people'),
('Demasiada', 'Too many (f)'),
('Ayudarle', 'Help you (formal)'),
('El teatro', 'The theatre'),
('De acuerdo.', 'Agreed. (lit: with agreement)');