// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyulaaievgvkfrwwhgrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5dWxhYWlldmd2a2Zyd3doZ3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTMxOTAsImV4cCI6MjA2NjA4OTE5MH0.kyHimBJ4yNf425vdgOg4Zq_kECmmjmKVLHq3PEM4CkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});